import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import Todos from "~/component/Todos";
import CreateTodo from "~/component/CreateTodo";

const Home: NextPage = () => {
  const {data: sessionData} = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#27025b] to-[#232439]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
         {sessionData && (
          <div className="grid grid-cols-1 gap-4 md:gap-8">
            <div className="flex flex-col gap-4 rounded-xl bg-white/10 p-4 text-white">
              <h3 className="text-xl font-bold">Todos</h3>
              <Todos/>
              <CreateTodo/>
            </div>
          </div>
         )}
          <div className="flex flex-col items-center gap-2">
          
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();


  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.email}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
